# -*- coding: utf-8 -*-
"""All Predicting Emotions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qnNIlcrbwamsQsbFCSBrH1cuF8s0e7BO
"""

import tensorflow as tf

# Get the GPU device name.
device_name = tf.test.gpu_device_name()

# The device name should look like the following:
if device_name == '/device:GPU:0':
    print('Found GPU at: {}'.format(device_name))
else:
    raise SystemError('GPU device not found')

import torch

# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

!pip install transformers

# Our data set!

# Access to resources
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

# Read data from file
import pandas as pd
from sklearn.utils import shuffle

# Point to the file in Google Drive
filename='/content/gdrive/My Drive/Parlamint/Predicting Emotions/EN/tweet_emotions.csv'
#filename='/content/gdrive/My Drive/EN_HS/big_dataset.csv'
tweet = pd.read_csv(filename, sep=',')

tweet.columns

tweet.head()

tweet['content'][4]

tweet.shape

tweet = tweet.reset_index(drop=True)
tweet.head()

tweet['sentiment'].value_counts()

tweet.loc[tweet['sentiment']=='happiness', 'label'] = 1
tweet.loc[tweet['sentiment']=='love', 'label'] = 1
tweet.loc[tweet['sentiment']=='hate', 'label'] = 0
tweet.loc[tweet['sentiment']=='anger', 'label'] = 0

tweet['label'].value_counts()

tweet3= tweet.query('label==1 or label==0')

tweet3.head()

tweet3[['label']]=tweet3[['label']].astype(int)

############ Reading the EN dataset

# en = pd.read_csv('/content/gdrive/My Drive/Parlamint/Sentiments/UK/all-data.csv', sep="\t", encoding="utf-8", error_bad_lines=False)
en = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/EN/second.csv', sep=",", encoding="utf-8", error_bad_lines=False)

en.head()

en.shape

en= en.rename(columns={'Column1': "content", "Column2": "sentiment"})

en.loc[en['sentiment']=='love', 'label'] = 1
en.loc[en['sentiment']=='anger', 'label'] = 0

en['sentiment'].value_counts()

en['label'].value_counts()

en3= en.query('label==1 or label==0')

en3.shape

############ Reading the EN dataset

# en = pd.read_csv('/content/gdrive/My Drive/Parlamint/Sentiments/UK/all-data.csv', sep="\t", encoding="utf-8", error_bad_lines=False)
go_emo = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/EN/go_emotion.txt', sep="\t", encoding="utf-8", error_bad_lines=False)

go_emo = go_emo.set_axis(['V', 'W', 'X'], axis=1, inplace=False)

go_emo['W'].head(20)

go_emo['V'][11]

go_emo= go_emo.rename(columns={'V': "content", "W": "sentiment"})

go_emo.loc[go_emo['sentiment']=='2', 'label'] = 0
go_emo.loc[go_emo['sentiment']=='11', 'label'] = 0
go_emo.loc[go_emo['sentiment']=='18', 'label'] = 1
go_emo.loc[go_emo['sentiment']=='20', 'label'] = 1

go_emo['sentiment'].value_counts().head(25)

go_emo['label'].value_counts()

go_emo3= go_emo.query('label==1 or label==0')

go_emo3.shape

go_emo3

go_emo3['content'][43372]

############ Reading the EN dataset

# en = pd.read_csv('/content/gdrive/My Drive/Parlamint/Sentiments/UK/all-data.csv', sep="\t", encoding="utf-8", error_bad_lines=False)
xed_en = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/EN/XED_en.txt', sep="\t", encoding="utf-8", error_bad_lines=False)

xed_en = xed_en.set_axis(['V', 'W'], axis=1, inplace=False)

xed_en.head()

xed_en= xed_en.rename(columns={'V': "content", "W": "sentiment"})

xed_en.loc[xed_en['sentiment']=='1', 'label'] = 0
xed_en.loc[xed_en['sentiment']=='3', 'label'] = 0
xed_en.loc[xed_en['sentiment']=='5', 'label'] = 1

xed_en['sentiment'].value_counts()

xed_en['label'].value_counts()

xed_en3= xed_en.query('label==1 or label==0')

xed_en3['content'][8217]

first = tweet3[["content","label"]]

second = en3[["content","label"]]

third = go_emo3[["content","label"]]

forth = xed_en3[["content","label"]]

first=first.reset_index(drop=True)
second=second.reset_index(drop=True)
third=third.reset_index(drop=True)
forth=forth.reset_index(drop=True)

all= pd.concat([first, second, third,forth], axis=0)

all[['label']]=all[['label']].astype(int)

all= all.reset_index(drop=True)

all['label'].value_counts()

all.shape

# train = pd.DataFrame(df4.iloc[:5002,:])
test = pd.DataFrame(all.iloc[500002:,:])

test.shape

# Get the lists of sentences and their labels.
sentences = all.content.values
labels = all.label.values

from transformers import BertTokenizer

# Load the BERT tokenizer.
print('Loading BERT tokenizer...')
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased', do_lower_case=True)

# Print the original sentence.
print(' Original: ', sentences[0])

# Print the sentence split into tokens.
print('Tokenized: ', tokenizer.tokenize(sentences[0]))

# Print the sentence mapped to token ids.
print('Token IDs: ', tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sentences[0])))

# Tokenize all of the sentences and map the tokens to thier word IDs.
input_ids = []

# For every sentence...
for sent in sentences:
    # `encode` will:
    #   (1) Tokenize the sentence.
    #   (2) Prepend the `[CLS]` token to the start.
    #   (3) Append the `[SEP]` token to the end.
    #   (4) Map tokens to their IDs.
    encoded_sent = tokenizer.encode(
                        sent,                      # Sentence to encode.
                        add_special_tokens = True, # Add '[CLS]' and '[SEP]'

                        # This function also supports truncation and conversion
                        # to pytorch tensors, but we need to do padding, so we
                        # can't use these features :( .
                        #max_length = 128,          # Truncate all sentences.
                        #return_tensors = 'pt',     # Return pytorch tensors.
                   )
    
    # Add the encoded sentence to the list.
    input_ids.append(encoded_sent)

# Print sentence 0, now as a list of IDs.
print('Original: ', sentences[1])
print('Token IDs:', input_ids[1])

print('Max sentence length: ', max([len(sen) for sen in input_ids]))

# We'll borrow the `pad_sequences` utility function to do this.
from keras.preprocessing.sequence import pad_sequences

# Set the maximum sequence length.
# I've chosen 64 somewhat arbitrarily. It's slightly larger than the
# maximum training sentence length of 47...
MAX_LEN = 64

print('\nPadding/truncating all sentences to %d values...' % MAX_LEN)

print('\nPadding token: "{:}", ID: {:}'.format(tokenizer.pad_token, tokenizer.pad_token_id))

# Pad our input tokens with value 0.
# "post" indicates that we want to pad and truncate at the end of the sequence,
# as opposed to the beginning.
input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", 
                          value=0, truncating="post", padding="post")

print('\nDone.')

# Create attention masks
attention_masks = []

# For each sentence...
for sent in input_ids:
    
    # Create the attention mask.
    #   - If a token ID is 0, then it's padding, set the mask to 0.
    #   - If a token ID is > 0, then it's a real token, set the mask to 1.
    att_mask = [int(token_id > 0) for token_id in sent]
    
    # Store the attention mask for this sentence.
    attention_masks.append(att_mask)

# Use train_test_split to split our data into train and validation sets for
# training
from sklearn.model_selection import train_test_split

# Use 80% for training and 10% for validation.
train_inputs, validation_inputs, train_labels, validation_labels = train_test_split(input_ids, labels, 
                                                            random_state=2018, test_size=0.1)
# Do the same for the masks.
train_masks, validation_masks, _, _ = train_test_split(attention_masks, labels,
                                             random_state=2018, test_size=0.1)

# Convert all inputs and labels into torch tensors, the required datatype 
# for our model.
train_inputs = torch.tensor(train_inputs)
validation_inputs = torch.tensor(validation_inputs)

train_labels = torch.tensor(train_labels)
validation_labels = torch.tensor(validation_labels)

train_masks = torch.tensor(train_masks)
validation_masks = torch.tensor(validation_masks)

from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler

# The DataLoader needs to know our batch size for training, so we specify it 
# here.
# For fine-tuning BERT on a specific task, the authors recommend a batch size of
# 16 or 32.

# We set all of the tweets into the batches
batch_size = 32

# Create the DataLoader for our training set.
train_data = TensorDataset(train_inputs, train_masks, train_labels)
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=batch_size)

# Create the DataLoader for our validation set.
validation_data = TensorDataset(validation_inputs, validation_masks, validation_labels)
validation_sampler = SequentialSampler(validation_data)
validation_dataloader = DataLoader(validation_data, sampler=validation_sampler, batch_size=batch_size)

train_inputs

# Loading BERT that we need!

from transformers import BertForSequenceClassification, AdamW, BertConfig

# Load BertForSequenceClassification, the pretrained BERT model with a single 
# linear classification layer on top. 
model = BertForSequenceClassification.from_pretrained(
    "bert-base-multilingual-cased", # Use the 12-layer BERT model, with an uncased vocab.
    num_labels = 2, # The number of output labels--2 for binary classification.
    #mnum_labels = 1, # The number of output labels--2 for binary classification.
                    # You can increase this for multi-class tasks.   
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
)

# Tell pytorch to run this model on the GPU.
model.cuda()

# Get all of the model's parameters as a list of tuples.
params = list(model.named_parameters())

print('The BERT model has {:} different named parameters.\n'.format(len(params)))

print('==== Embedding Layer ====\n')

for p in params[0:5]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

print('\n==== First Transformer ====\n')

for p in params[5:21]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

print('\n==== Output Layer ====\n')

for p in params[-4:]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

optimizer = AdamW(model.parameters(),
                  lr = 2e-5, # args.learning_rate - default is 5e-5, our notebook had 2e-5
                  eps = 1e-8 # args.adam_epsilon  - default is 1e-8.
                )

from transformers import get_linear_schedule_with_warmup

# Number of training epochs (authors recommend between 2 and 4)
epochs = 4

# Total number of training steps is number of batches * number of epochs.
total_steps = len(train_dataloader) * epochs

# Create the learning rate scheduler.
scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = 0, # Default value in run_glue.py
                                            num_training_steps = total_steps)

import numpy as np

# Function to calculate the accuracy of our predictions vs labels
def flat_accuracy(preds, labels):
    pred_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return np.sum(pred_flat == labels_flat) / len(labels_flat)

import time
import datetime

def format_time(elapsed):
    '''
    Takes a time in seconds and returns a string hh:mm:ss
    '''
    # Round to the nearest second.
    elapsed_rounded = int(round((elapsed)))
    
    # Format as hh:mm:ss
    return str(datetime.timedelta(seconds=elapsed_rounded))

# Fine tuning!

import random

# This training code is based on the `run_glue.py` script here:
# https://github.com/huggingface/transformers/blob/5bfcd0485ece086ebcbed2d008813037968a9e58/examples/run_glue.py#L128


# Set the seed value all over the place to make this reproducible.
seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

# Store the average loss after each epoch so we can plot them.
loss_values = []


# For each epoch...
for epoch_i in range(0, epochs):
    
    # ========================================
    #               Training
    # ========================================
    
    # Perform one full pass over the training set.

    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    # Measure how long the training epoch takes.
    t0 = time.time()

    # Reset the total loss for this epoch.
    total_loss = 0

    # Put the model into training mode. Don't be mislead--the call to 
    # `train` just changes the *mode*, it doesn't *perform* the training.
    # `dropout` and `batchnorm` layers behave differently during training
    # vs. test (source: https://stackoverflow.com/questions/51433378/what-does-model-train-do-in-pytorch)
    model.train()

    # For each batch of training data...
    for step, batch in enumerate(train_dataloader):

        # Progress update every 40 batches.
        if step % 40 == 0 and not step == 0:
            # Calculate elapsed time in minutes.
            elapsed = format_time(time.time() - t0)
            
            # Report progress.
            print('  Batch {:>5,}  of  {:>5,}.    Elapsed: {:}.'.format(step, len(train_dataloader), elapsed))

        # Unpack this training batch from our dataloader. 
        #
        # As we unpack the batch, we'll also copy each tensor to the GPU using the 
        # `to` method.
        #
        # `batch` contains three pytorch tensors:
        #   [0]: input ids 
        #   [1]: attention masks
        #   [2]: labels 
        b_input_ids = batch[0].to(device)
        b_input_mask = batch[1].to(device)
        b_labels = batch[2].to(device)

        # Always clear any previously calculated gradients before performing a
        # backward pass. PyTorch doesn't do this automatically because 
        # accumulating the gradients is "convenient while training RNNs". 
        # (source: https://stackoverflow.com/questions/48001598/why-do-we-need-to-call-zero-grad-in-pytorch)
        model.zero_grad()        

        # Perform a forward pass (evaluate the model on this training batch).
        # This will return the loss (rather than the model output) because we
        # have provided the `labels`.
        # The documentation for this `model` function is here: 
        # https://huggingface.co/transformers/v2.2.0/model_doc/bert.html#transformers.BertForSequenceClassification
        outputs = model(b_input_ids, 
                    token_type_ids=None, 
                    attention_mask=b_input_mask, 
                    labels=b_labels)
        
        # The call to `model` always returns a tuple, so we need to pull the 
        # loss value out of the tuple.
        loss = outputs[0]

        # Accumulate the training loss over all of the batches so that we can
        # calculate the average loss at the end. `loss` is a Tensor containing a
        # single value; the `.item()` function just returns the Python value 
        # from the tensor.
        total_loss += loss.item()

        # Perform a backward pass to calculate the gradients.
        loss.backward()

        # Clip the norm of the gradients to 1.0.
        # This is to help prevent the "exploding gradients" problem.
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        # Update parameters and take a step using the computed gradient.
        # The optimizer dictates the "update rule"--how the parameters are
        # modified based on their gradients, the learning rate, etc.
        optimizer.step()

        # Update the learning rate.
        scheduler.step()

    # Calculate the average loss over the training data.
    avg_train_loss = total_loss / len(train_dataloader)            
    
    # Store the loss value for plotting the learning curve.
    loss_values.append(avg_train_loss)

    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epcoh took: {:}".format(format_time(time.time() - t0)))
        
    # ========================================
    #               Validation
    # ========================================
    # After the completion of each training epoch, measure our performance on
    # our validation set.

    print("")
    print("Running Validation...")

    t0 = time.time()

    # Put the model in evaluation mode--the dropout layers behave differently
    # during evaluation.
    model.eval()

    # Tracking variables 
    eval_loss, eval_accuracy = 0, 0
    nb_eval_steps, nb_eval_examples = 0, 0

    # Evaluate data for one epoch
    for batch in validation_dataloader:
        
        # Add batch to GPU
        batch = tuple(t.to(device) for t in batch)
        
        # Unpack the inputs from our dataloader
        b_input_ids, b_input_mask, b_labels = batch
        
        # Telling the model not to compute or store gradients, saving memory and
        # speeding up validation
        with torch.no_grad():        

            # Forward pass, calculate logit predictions.
            # This will return the logits rather than the loss because we have
            # not provided labels.
            # token_type_ids is the same as the "segment ids", which 
            # differentiates sentence 1 and 2 in 2-sentence tasks.
            # The documentation for this `model` function is here: 
            # https://huggingface.co/transformers/v2.2.0/model_doc/bert.html#transformers.BertForSequenceClassification
            outputs = model(b_input_ids, 
                            token_type_ids=None, 
                            attention_mask=b_input_mask)
        
        # Get the "logits" output by the model. The "logits" are the output
        # values prior to applying an activation function like the softmax.
        logits = outputs[0]

        # Move logits and labels to CPU
        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()
        
        # Calculate the accuracy for this batch of test sentences.
        tmp_eval_accuracy = flat_accuracy(logits, label_ids)
        
        # Accumulate the total accuracy.
        eval_accuracy += tmp_eval_accuracy

        # Track the number of batches
        nb_eval_steps += 1

    # Report the final accuracy for this validation run.
    print("  Accuracy: {0:.2f}".format(eval_accuracy/nb_eval_steps))
    print("  Validation took: {:}".format(format_time(time.time() - t0)))

print("")
print("Training complete!")

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# % matplotlib inline

import seaborn as sns

# Use plot styling from seaborn.
sns.set(style='darkgrid')

# Increase the plot size and font size.
sns.set(font_scale=1.5)
plt.rcParams["figure.figsize"] = (12,6)

# Plot the learning curve.
plt.plot(loss_values, 'b-o')

# Label the plot.
plt.title("Training loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.show()

# full.to_csv(r'/content/gdrive/My Drive/Text Summarization/full_new.csv')

import pandas as pd

# new = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/BG/bg_tot2.txt', sep="\t", encoding="utf-8",error_bad_lines=False)
# new = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/CZ/total_cz.txt', sep="\t", encoding="utf-8",error_bad_lines=False)
# new = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/ES/es_total.txt', sep="\t", encoding="utf-8",error_bad_lines=False)
# new = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/FR/tot2.txt', sep="\t", encoding="utf-8",error_bad_lines=False)
# new = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/SLO/tot_before_cut.txt', sep=",", encoding="utf-8",error_bad_lines=False)
new = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/UK/tot2.txt', sep="\t", encoding="utf-8",error_bad_lines=False)

# new = pd.read_csv('/content/gdrive/My Drive/Parlamint/Predicting Emotions/SLO/tot_before_cut.txt', sep=",", encoding="utf-8",error_bad_lines=False)

new

# new['SPEAKER_GENDER']

new.loc[new['Speaker_gender']=='M', 'label'] = 1
new.loc[new['Speaker_gender']=='F', 'label'] = 0
# new.loc[new['SPEAKER_GENDER']=='M', 'label'] = 1
# new.loc[new['SPEAKER_GENDER']=='F', 'label'] = 0

new['label'].value_counts()

new3= new.query('label==1 or label==0')

new3[['label']]=new3[['label']].astype(int)

new3.columns

new_df = new3[new3['Speaker_role'] == 'Regular']
new_df2 = new_df[new_df['Speaker_type'] == 'MP']
# new_df = new3[new3['SPEAKER_ROLE'] == 'regular']
# new_df2 = new_df[new_df['SPEAKER_TYPE'] == 'MP']

print(new_df2.shape)
print(new_df.shape)
print(new3.shape)

# Clening based on length
new_df2['count']=new_df2["V2"].apply(lambda x: len(str(x).split(' ')))

new_df3 = new_df2[new_df2['count'] > 10]

print(new_df2.shape)
print(new_df3.shape)

# new2 = pd.DataFrame(new3.iloc[:15000,:])
new2= new_df3.sample(n=10000)
# new2=new3

new2['label'].value_counts()

new2.head()

import numpy as np

def softmax(x):

    e_x = np.exp(x - np.max(x))

    return e_x / e_x.sum()

from scipy.special import softmax

# Test Dataset!

import pandas as pd

# Load the dataset into a pandas dataframe.
#df = pd.read_csv("./cola_public/raw/out_of_domain_dev.tsv", delimiter='\t', header=None, names=['sentence_source', 'label', 'label_notes', 'sentence'])
df= new2
# Report the number of sentences.
print('Number of test sentences: {:,}\n'.format(df.shape[0]))

# Create sentence and label lists
sentences = df.V2.values
labels = df.label.values

# Tokenize all of the sentences and map the tokens to thier word IDs.
input_ids = []

# For every sentence...
for sent in sentences:
    # `encode` will:
    #   (1) Tokenize the sentence.
    #   (2) Prepend the `[CLS]` token to the start.
    #   (3) Append the `[SEP]` token to the end.
    #   (4) Map tokens to their IDs.
    encoded_sent = tokenizer.encode(
                        sent,                      # Sentence to encode.
                        add_special_tokens = True, # Add '[CLS]' and '[SEP]'
                   )
    
    input_ids.append(encoded_sent)

# Pad our input tokens
input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, 
                          dtype="long", truncating="post", padding="post")

# Create attention masks
attention_masks = []

# Create a mask of 1s for each token followed by 0s for padding
for seq in input_ids:
  seq_mask = [float(i>0) for i in seq]
  attention_masks.append(seq_mask) 

# Convert to tensors.
prediction_inputs = torch.tensor(input_ids)
prediction_masks = torch.tensor(attention_masks)
prediction_labels = torch.tensor(labels)

# Set the batch size.  
batch_size = 2 

# Create the DataLoader.
prediction_data = TensorDataset(prediction_inputs, prediction_masks, prediction_labels)
prediction_sampler = SequentialSampler(prediction_data)
prediction_dataloader = DataLoader(prediction_data, 
                                   sampler=prediction_sampler,
                                   batch_size=batch_size)

# Prediction on test set
import numpy as np

print('Predicting labels for {:,} test sentences...'.format(len(prediction_inputs)))

# Put model in evaluation mode
model.eval()

# Tracking variables 
predictions , true_labels = [], []

# Predict 
# y= []
y= pd.DataFrame()
for batch in prediction_dataloader:
  # Add batch to GPU
  batch = tuple(t.to(device) for t in batch)
  
  # Unpack the inputs from our dataloader
  b_input_ids, b_input_mask, b_labels = batch
  
  # Telling the model not to compute or store gradients, saving memory and 
  # speeding up prediction
  with torch.no_grad():
      # Forward pass, calculate logit predictions
      outputs = model(b_input_ids, token_type_ids=None, 
                      attention_mask=b_input_mask)

  logits = outputs[0]

  # Multiple predictions
  pred=[]
  collect=[]
  p=[]
  #w=[]
  w = pd.DataFrame()



  for _ in range(1):
            model.train()
            pred = model(b_input_ids, token_type_ids=None, 
                      attention_mask=b_input_mask)
            p=pred[0].detach().cpu().numpy()
            x = np.reshape(p, (2, 2))
            x = pd.DataFrame(x)
            x2 = softmax(x, axis=1)
            x3 = x2.drop([0], axis=1)
            #x3 = x.drop([0], axis=1)
            w = pd.concat([w, x3], axis=1, ignore_index=True)
            #collect.append(x3)

            # collect.append(np.matrix(p)

#   x = np.reshape(collect, (40, 2))
#   x = pd.DataFrame(x)
#   x2 = softmax(x, axis=1)
#   x3 = x2.drop([1], axis=1)
  w = pd.DataFrame(w)
  y = y.append(w)

  
#   # Move logits and labels to CPU
  logits = logits.detach().cpu().numpy()
  label_ids = b_labels.to('cpu').numpy()
  
#   # Store predictions and true labels
  predictions.append(logits)
  true_labels.append(label_ids)

print('    DONE.')

y=y.reset_index(drop=True)
y

#MC_pred = test.reshape(100,1000)
#pred=pd.DataFrame(MC_pred)
means=y.mean(axis=1)
type(means)
print(len(means))
print(means)

means[means >= 0.5] = 1
means[means < 0.5] = 0

print(means)

means.value_counts()

y=y.reset_index(drop=True)
new2=new2.reset_index(drop=True)
# y

full = pd.concat([new2,y], axis=1, sort=False)

# full.head()

full.rename(columns = {0:'y'}, inplace = True)

# full.to_csv(r'/content/gdrive/My Drive/Parlamint/Predicting Emotions/Dataset Results/si_emo_results.csv')

# full
full.loc[full['y']<0.0015, 'anger'] = 1

full['anger'].value_counts()

ang= full.query('anger==1')

ang.shape

ang=ang.reset_index(drop=True)

ang['V2'][1]